### ISSUE TITLE
Ticking Tile Entity Crash

### ISSUE THREAD

**Issue by AhmiDarrow** [CelesTek-Team/HexCraft#8] opened 2015-11-26 00:22 UTC
Yes I tried to add this mod in as I LOVE everything I'm seeing about it but sadly I get a ticking tile entity crash from custom npc's that only happens once I add in HexCraft.
 Crash Log - http://pastebin.com/hhKSJkMj

I really want to add this in, is this something you can fix on your side or? Let me know if you need anything else.

**Comment by AhmiDarrow** [comment] 2015-11-26 01:29
So upon further testing I removed the custom npc entities and it works so as stated on the release about tile entities just didn't expect that to cross over to other mods. I'll let Noppes know about it as well.

**Comment by CelesTek-Team** [comment] 2015-11-26 09:22
This crash doesn't appear to have anything to do with HEXCraft and is probably just a coincidence that it happened after you added it in. If you look at the stack trace, you won't see HEXCraft being mentioned anywhere. Instead, this issue seems to be related with PneumatiCraft (pneumaticCraft.common.block.BlockPressureTube), probably having some incompatibility with Custom NPCs. 
We suggest trying to put the NPCs back in and trying to add/remove HEXCraft multiple times just to see if the issue still comes up even when HEXCraft is not added. We are not modifying anything related to NPCs, so there should be no way that it is related. However, we will keep the issue open for now, if you find anything.

**Comment by AhmiDarrow** [comment] 2015-11-27 05:47
I removed the files related to the saved world data involved with entities in custom NPC's and will just have to add them back in using that data, but for sure something about the way Noppes handles Ticking Tile Entities is affected by HexCraft or vice versa. I've run 9 test's and the only version of this crash comes when I have saved data from Custom NPC's meaning NPC's in the world and it tries to load with NPC data created before HexCraft was added. Previously created "cloned" NPC's even are re-add-able but ANY Custom NPC I had placed Preload creates a ticking tile entity crash but only with HexCraft. Easily fixed via simple replacement but wanted to let you know, I also have mentioned to Noppes and will let Martin know by the weekend.

**Comment by CelesTek-Team** [comment] 2015-11-27 06:06
Interesting. Did you try pulling PneumaticCraft out of the pack and trying again? The weird part of the crash log is that it says that it is caused by PneumaticCraft, and not HEXCraft, and that is a little bit confusing.

**Comment by AhmiDarrow** [comment] 2015-11-27 07:31
I have not I'll re-test and let you know the results.

**Comment by CelesTek-Team** [comment] 2015-12-10 00:38
Have you managed to find anything out?

**Comment by CelesTek-Team** [comment] 2015-12-22 01:05
We will close this for now, but in case you find anything useful, please let us know and we can reopen it!

**Closed as completed by CelesTek-Team** 2015-12-22 01:05 UTC
